// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8SPv6OVSEvZhD__SbD2ruqRLiH8yEpVk',
    appId: '1:58861564595:web:0eaa3befc0cf1e597376c6',
    messagingSenderId: '58861564595',
    projectId: 'man-city-6cdb9',
    authDomain: 'man-city-6cdb9.firebaseapp.com',
    storageBucket: 'man-city-6cdb9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDzrXUREcvDDo98njO9NLcv09Epo7swUY',
    appId: '1:58861564595:android:e3de9d5a2653e4a97376c6',
    messagingSenderId: '58861564595',
    projectId: 'man-city-6cdb9',
    storageBucket: 'man-city-6cdb9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPqL6_jnNrgCri0lnQb4TgfXL-Iu1bjHY',
    appId: '1:58861564595:ios:d52f5f044487e5067376c6',
    messagingSenderId: '58861564595',
    projectId: 'man-city-6cdb9',
    storageBucket: 'man-city-6cdb9.appspot.com',
    iosClientId: '58861564595-qb64cv8hsj50bqld4bu2dmqo407dcjqc.apps.googleusercontent.com',
    iosBundleId: 'com.example.mancityfc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPqL6_jnNrgCri0lnQb4TgfXL-Iu1bjHY',
    appId: '1:58861564595:ios:bbca050ebd0fb0797376c6',
    messagingSenderId: '58861564595',
    projectId: 'man-city-6cdb9',
    storageBucket: 'man-city-6cdb9.appspot.com',
    iosClientId: '58861564595-48bpmuo02hap30l7thm51t4s7h1a41dp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mancityfc.RunnerTests',
  );
}
